language: swift
osx_image: xcode10.2

branches:
  only:
    - docs
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.6.2
  - gem install cocoapods
  - gem install xcpretty -N
  - make bootstrap
after_success:
  - gem install jazzy
  - make documentation
script:
  - set -o pipefail
  - make build
  - make test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: docs